name: SimpleTeleport
author: iam57
version: '${version}'
main: com.iam57.simpleteleport.SimpleTeleport
api-version: '1.20'
commands:
  tpa:
    description: 请求传送到一个玩家
    usage: /tpa <玩家>
  tpahere:
    description: 请求一个玩家传送到你这里
    usage: /tpahere <玩家>
  tpaccept:
    description: 接受一个传送请求
    usage: /tpaccept
  tpdeny:
    description: 拒绝一个传送请求
    usage: /tpdeny